- 9월 배포 관련 roleId 글자수 제한 변경 및 특수문자 추가 허용
TOAST-DOCS/ROLE pull request #1
Opened 2023-09-07 00:43 UTC by hyunjoo-yi

* 연관 테스크 : [[Role] Role 생성 시, role id 에 일부 특수문자 포함 및 role_id 컬럼 사이즈 변경](https://nhnent.dooray.com/task/1963480696738741170/3621235395105168042)
* 💡 마일스톤을 **9월 26일**로 지정했는데, role hotfix 배포에 맞춰 변경되어야 하면 코멘트 부탁드립니다.

2023-09-07 00:47 UTC, ByoungGeol-Cho requested changes
(MUST) 릴리즈 노트에도 추가 부탁드립니다.

2023-09-07 01:23 UTC, hyunjoo-yi commented
> (MUST) 릴리즈 노트에도 추가 부탁드립니다.

https://github.com/TOAST-DOCS/ROLE/pull/1/commits/d9a096183851748a2d5304099d7d9bb168772895 에 반영했습니다.

2023-09-10 23:53 UTC, tw-sunyoung commented on ko/release-notes.md
> +### 2023.09.26
### 2023.09.26 -> 2023. 09. 26.
: 날짜 표기 규칙(yyyy. mm. dd.)에 따라 연, 월, 일 사이에 공백을 추가하고, 일자 뒤에도 마침표를 추가하고자 합니다.

@hyunjoo-yi 선임님, 안녕하세요!
본 문서를 살펴 보니 이전 버전에도 날짜 표기가 규칙과 다르게 yyyy.mm.dd 로 되어 있는 것으로 보이는데요, 혹시 본 건을 적용하실 때 함께 일괄 수정해 주실 수 있으실지 검토 부탁드리겠습니다. 감사합니다.

2023-09-11 00:08 UTC, tw-sunyoung commented on ko/api-guide.md
>  |roleGroup|	String|	No|	Role Group <br/> Role들을 그룹핑하여 관리 목적으로 사용할수 있다. 최대 128글자까지 등록 가능하다.|
사용할수 있다. -> 사용할 수 있다.
: 띄어쓰기를 수정하고자 합니다.

2023-09-11 00:34 UTC, hyunjoo-yi commented on ko/release-notes.md
> +### 2023.09.26
@tw-sunyoung 전임님, 안녕하세요!
말씀해주신 날짜 부분을 https://github.com/TOAST-DOCS/ROLE/pull/1/commits/260d852cfd6e4714e41b95a26a7cc3ba125a9578 에서 일괄 변영했습니다.
감사합니다.

2023-09-11 00:34 UTC, hyunjoo-yi commented on ko/api-guide.md
>  |roleGroup|	String|	No|	Role Group <br/> Role들을 그룹핑하여 관리 목적으로 사용할수 있다. 최대 128글자까지 등록 가능하다.|
https://github.com/TOAST-DOCS/ROLE/pull/1/commits/044889a8a557b986ac4b56f2c6b5ade3474a970c 에서 띄어쓰기 부분을 반영하였습니다.

2023-09-11 01:02 UTC, tw-sunyoung commented on ko/release-notes.md
> +    * 기존에는 `_`와 `-` 만 허용되던 특수문자가 `.`와 `:`도 허용되도록 추가되었습니다.
`-` 만 -> `-`만
: 조사 앞 공백을 삭제하고자 합니다.

2023-09-11 01:08 UTC, hyunjoo-yi commented on ko/release-notes.md
> +    * 기존에는 `_`와 `-` 만 허용되던 특수문자가 `.`와 `:`도 허용되도록 추가되었습니다.
https://github.com/TOAST-DOCS/ROLE/pull/1/commits/c1dde7acb5633559e0edb53b59039d851090ebf0 에서 반영했습니다.

2023-09-11 01:18 UTC, merged